server:
  port: 8080
  tomcat:
    maxConnections: 100

logging:
  level:
    alen.demo: info
  file:
    name: demo.log
    path: log

api:
  province: http://www.weather.com.cn/data/city3jdata/china.html
  city: http://www.weather.com.cn/data/city3jdata/provshi/
  country: http://www.weather.com.cn/data/city3jdata/station/
  weather: http://www.weather.com.cn/data/sk/

spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
